targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/config/*.dart

        options:
          explicit_to_json: true
          include_if_null: true
          any_map: true
          field_rename: snake

      autoequal_gen:
        enabled: true
        options:
          auto_include: true
